name: bld-ci

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build-bld-project:
    strategy:
      matrix:
        java-version: [ 17, 21, 25 ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v5
        with:
          distribution: "zulu"
          java-version: ${{ matrix.java-version }}

      - name: Download dependencies [examples]
        working-directory: examples
        run: ./bld download

      - name: Run tests [examples]
        working-directory: examples
        run: ./bld compile test

      - name: Compile and create the JAR [examples]
        working-directory: examples
        run: ./bld compile bootjar

      - name: Compile and create the WAR [examples]
        working-directory: examples
        run: ./bld compile bootwar

      - name: Download dependencies
        run: ./bld download

      - name: Compile source code
        run: ./bld compile

      - name: Run tests
        id: tests
        run: ./bld test

      - name: Run reporter
        if: ${{ failure() && steps.tests.outcome == 'failure' }}
        run: ./bld reporter --all