name: bld-ci

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build-bld-project:
    strategy:
      matrix:
        java-version: [ 17, 21, 25 ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v5
        with:
          distribution: "zulu"
          java-version: ${{ matrix.java-version }}

      - name: Download dependencies [examples 3.5.x]
        working-directory: examples/3.5.x
        run: ./bld download

      - name: Compile source [examples 3.5.x]
        working-directory: examples/3.5.x
        run: ./bld compile

      - name: Run tests [examples 3.5.x]
        working-directory: examples/3.5.x
        run: ./bld test

      - name: Compile and create the JAR [examples 3.5.x]
        working-directory: examples/3.5.x
        run: ./bld bootjar

      - name: Compile and create the WAR [examples 3.5.x]
        working-directory: examples/3.5.x
        run: ./bld bootwar

      - name: Download dependencies [examples 4.0.x]
        working-directory: examples/4.0.x
        run: ./bld download

      - name: Compile source [examples 4.0.x]
        working-directory: examples/4.0.x
        run: ./bld compile

      - name: Run tests [examples 4.0.x]
        working-directory: examples/4.0.x
        run: ./bld test

      - name: Compile and create the JAR [examples 4.0.x]
        working-directory: examples/4.0.x
        run: ./bld bootjar

      - name: Compile and create the WAR [examples 4.0.x]
        working-directory: examples/4.0.x
        run: ./bld bootwar

      - name: Download dependencies
        run: ./bld download

      - name: Compile source code
        run: ./bld compile

      - name: Run tests
        id: tests
        run: ./bld test

      - name: Run reporter
        if: always() && steps.tests.outcome == 'failure'
        run: ./bld reporter --all